### ISSUE TITLE
assets 

### ISSUE THREAD

**Issue by rizaljamjam** [Imperial-lord/mapbox-flutter#10]
Hi, Imperial Lord

On the source code, you gave the assets for env. are missing 
So I think maybe you have to re-uploading the source code, but thank you for your tutorial, that it's good.

This is the image from your youtube tutorial 
<img width="285" alt="Screen Shot 2022-05-11 at 19 37 38" src="https://user-images.githubusercontent.com/47346980/167852290-8d6d0dcd-942b-4e82-b0e9-e7f6178b1a1b.png">

This is the image from your github 
<img width="1263" alt="Screen Shot 2022-05-11 at 19 48 24" src="https://user-images.githubusercontent.com/47346980/167853632-14f7bbc3-196c-436e-b11d-55a57cc8a8f9.png">

Thank you for your attention and your time
Regards

**Comment by Imperial-lord** [comment]
I have created a new file. Thanks for pointing this out.
