### ISSUE TITLE
Everyone Please modify 

### ISSUE THREAD

**Issue by Manishmg3994** [Imperial-lord/mapbox-flutter#35]
repositories {
        google()
        mavenCentral()
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = "mapbox"
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN']
            }
        }
    }

**Comment by Manishmg3994** [comment]
```
 repositories {
        google()
        mavenCentral()
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = "mapbox"
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN']
            }
        }
    }
```

**Comment by sumanbalayar08** [comment]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (23507): Receiver: null
E/flutter (23507): Tried calling: []("routes")
E/flutter (23507): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (23507): #1      getDirectionsAPIResponse
directions_handler.dart:12
E/flutter (23507): <asynchronous suspension>
E/flutter (23507): #2      _SplashScreenState.initializeLocationAndSave
splashscreen.dart:53
E/flutter (23507): <asynchronous suspension>

**Comment by Manishmg3994** [comment]
@sumanbalayar08  Already Modified in new Package update (**thanks to @Imperial-lord  ) , now there is no need of adding above stuff just need to add secret token  in gradle.properties as the password with name 'MAPBOX_DOWNLOADS_TOKEN' and also modify some .xml ,or say try adding new one
